name: view_model_macro
description: "Experimental support for ViewModel classes in Dart using pckg:macros."
version: 0.0.1
repository: https://github.com/alvarobcprado/view_model_macro
topics: [macros, view-model]

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  macros: ^0.1.0-main.5

dev_dependencies:
  very_good_analysis: ^6.0.0
